### ISSUE TITLE
On the win platform, holab cannot be installed correctly

### ISSUE THREAD

**Issue by quanhao129611** [ucl-bug/holab#20]
Hi,

I am trying to install the holab library from GitHub. After installing jax with GPU support, I can successfully install holab using pip install holab. However, when I import holab, I get the following error:

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\12433\.conda\envs\jaxholab\lib\site-packages\holab\__init__.py", line 1, in <module>
    from . import losses, materials
  File "C:\Users\12433\.conda\envs\jaxholab\lib\site-packages\holab\losses.py", line 6, in <module>
    from jwave import FourierSeries
  File "C:\Users\12433\.conda\envs\jaxholab\lib\site-packages\jwave\__init__.py", line 19, in <module>
    from jwave import acoustics as ac
  File "C:\Users\12433\.conda\envs\jaxholab\lib\site-packages\jwave\acoustics\__init__.py", line 17, in <module>
    from .operators import *
  File "C:\Users\12433\.conda\envs\jaxholab\lib\site-packages\jwave\acoustics\operators.py", line 23, in <module>
    from jwave.geometry import Medium
  File "C:\Users\12433\.conda\envs\jaxholab\lib\site-packages\jwave\geometry.py", line 26, in <module>
    from plum import parametric, type_of
ImportError: cannot import name 'type_of' from 'plum' (C:\Users\12433\.conda\envs\jaxholab\lib\site-packages\plum\__init__.py)
```

It seems that this is caused by the incompatible versions of the plum package. I fixed the version of plum, but then I got the error that the jaxdf and plum versions are incompatible. Can you provide the specific versions of the libraries required by holab? I am currently unable to resolve the version mismatch issue.

Thank you very much.

**Comment by astanziola** [comment]
Hi @quanhao129611 , apologies if this took so long and thank you for the very kind words! 
This was a probem on `jwave`'s end, and should be fixed now if you install the latest version of `jwave`. Please let me know if that's not the case and feel free to reopen this if you find any issue.
